language: elixir

elixir:
  - 1.6.0

otp_release:
  - 19.0

env:
  - MIX_ENV=test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - MIX_ENV=test mix deps.get
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
