language: elixir

elixir:
  - 1.9.2

otp_release:
  - 2.1.3

env:
  - MIX_ENV=test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - MIX_ENV=test mix deps.get
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
